# Generated by Django 3.2.16 on 2023-01-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('name', models.CharField(max_length=32, verbose_name='收货人')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
            ],
            options={
                'verbose_name': '收货地址表',
                'verbose_name_plural': '收货地址表',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(max_length=128, verbose_name='图片1')),
                ('image2', models.CharField(max_length=128, verbose_name='图片2')),
            ],
            options={
                'verbose_name': '轮播图表',
                'verbose_name_plural': '轮播图表',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='书名')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('price', models.CharField(max_length=32, verbose_name='价格')),
                ('publish', models.CharField(max_length=32, verbose_name='出版社')),
                ('publish_date', models.DateField(verbose_name='出版日期')),
                ('cover', models.CharField(max_length=128, verbose_name='封面')),
                ('desc', models.TextField(verbose_name='简介')),
                ('category', models.CharField(max_length=32, verbose_name='分类')),
                ('sales', models.DateField(verbose_name='销量')),
                ('statue', models.CharField(max_length=32, verbose_name='状态')),
            ],
            options={
                'verbose_name': '书籍表',
                'verbose_name_plural': '书籍表',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '书籍分类表',
                'verbose_name_plural': '书籍分类表',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('book', models.CharField(max_length=32, verbose_name='书名')),
                ('cover', models.CharField(max_length=128, verbose_name='封面')),
                ('price', models.CharField(max_length=32, verbose_name='价格')),
                ('count', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '购物车表',
                'verbose_name_plural': '购物车表',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('book', models.CharField(max_length=32, verbose_name='书名')),
                ('time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '书籍收藏表',
                'verbose_name_plural': '书籍收藏表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('book', models.CharField(max_length=32, verbose_name='书名')),
                ('content', models.TextField(verbose_name='内容')),
                ('time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '书籍评论表',
                'verbose_name_plural': '书籍评论表',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('price', models.CharField(max_length=32, verbose_name='价格')),
                ('book', models.CharField(max_length=32, verbose_name='书名')),
                ('time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '优惠券表',
                'verbose_name_plural': '优惠券表',
            },
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='优惠券码')),
                ('price', models.CharField(max_length=32, verbose_name='价格')),
                ('book', models.CharField(max_length=32, verbose_name='书名')),
                ('time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '优惠券码表',
                'verbose_name_plural': '优惠券码表',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('book', models.CharField(max_length=32, verbose_name='书名')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('price', models.CharField(max_length=32, verbose_name='价格')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
                ('ordertime', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
