# Generated by Django 3.2.16 on 2023-01-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_alter_book_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordertime',
            field=models.DateField(verbose_name='下单时间'),
        ),
    ]
