# Generated by Django 3.2.16 on 2023-01-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_alter_order_ordertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordertime',
            field=models.DateField(verbose_name='下单时间'),
        ),
    ]
