# Generated by Django 3.2.1 on 2023-04-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0007_auto_20230428_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '水果管理', 'verbose_name_plural': '水果管理'},
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.CharField(default=1, max_length=32, verbose_name='用户名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sjuser',
            field=models.CharField(default=1, max_length=32, verbose_name='批发商名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='book',
            field=models.CharField(max_length=32, verbose_name='水果名'),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='book',
            field=models.CharField(max_length=32, verbose_name='水果名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.CharField(max_length=32, verbose_name='水果名'),
        ),
    ]
