# Generated by Django 3.2.1 on 2023-04-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0008_auto_20230428_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='sjuser',
        ),
    ]
