# Generated by Django 3.2.1 on 2023-04-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0009_rename_user_book_sjuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(upload_to='templates/assets', verbose_name='封面'),
        ),
    ]
